### ISSUE TITLE
I don't notice the Task-driven function anywhere.

### ISSUE THREAD

**Issue by Huynh-Chinh** [yaoxingcheng/TLM#10]
Hi yaoxingcheng,

Thanks for releasing the code and paper for your task-driven language modeling approach.

I tried running your code.
But I don't notice the Task-driven functionality anywhere.
Can you explain a little more the difference between having Task-driven and traditional LM training?
thank you very much.

Best,
ChinhH
![framework](https://user-images.githubusercontent.com/61222689/153240586-94e89641-ffa5-4ffe-8e41-c2c286456d0e.png)

**Comment by yaoxingcheng** [comment]
Hi ChinhH. In the released code, data selection is decomposed from LM training. You can read the scripts in `src/data_selection.py` to see how task data is used to retrieve similar data from general corpus (which is one of the key differences between TLM and PLM). Also, in line 113 of the code in `src/model.py`, you can see the loss of the model is an weighted average of task objective and LM objective. Such multi-task learning scheme is also one of the points that makes a difference.

**Comment by Huynh-Chinh** [comment]
thanks for your support.
I have 1 question about data set to train Language Modeling. Is it generated from source.csv+selected.csv ?
![Screenshot from 2022-02-16 09-58-32](https://user-images.githubusercontent.com/61222689/154187798-61a56769-2b0e-48aa-9625-a75ab9ec55ef.png)

**Comment by yaoxingcheng** [comment]
We only use selected data (in your case `selected_rake.csv`) as the external data for language modeling

**Comment by Huynh-Chinh** [comment]
Thanks for your answer
