### ISSUE TITLE
如何下载CC-Stories语料

### ISSUE THREAD

**Issue by sunyilgdx** [yaoxingcheng/TLM#11]
请问如何下载到CC-Stories语料库呢？

**Comment by yaoxingcheng** [comment]
We haven't found a publicly available version of STORIES yet. In our work, we follow the same methodology in [the original paper of STORIES dataset](https://arxiv.org/pdf/1806.02847.pdf) (Section 5.3) to collect a set of documents with a similar size from the CommonCrawl corpus, and use that collected documents as part of our general corpus.
