### ISSUE TITLE
"the client failed to establish a connection"

### ISSUE THREAD

**Issue by Jesse1eung** [yaoxingcheng/TLM#16]
hi xingcheng, i try to use example script you provided, that is "curl -H ... ...ngrok.io/search", but it returned something like "Failed to complete tunnel connection". could you give me some help? thanks !!!

**Comment by yaoxingcheng** [comment]
Oh, I'm so sorry. Due to the lack of resources both in machines and in human, the data retrieval service is no longer maintained. I've already modified that part in README.
