### ISSUE TITLE
add web demo/models/datasets to ICML organization on Hugging Face

### ISSUE THREAD

**Issue by AK391** [yaoxingcheng/TLM#17]
Hi, I see you have already submitted models for this paper on Hugging Face at https://huggingface.co/yxchar, congrats for the acceptance at ICML. We are having a event on Hugging Face for ICML 2022, where you can submit spaces(web demos), models, and datasets for papers for a chance to win prizes. For the existing models, you can clone them and push them to the ICML 2022 organization here: https://huggingface.co/ICML2022, after joining the organization using this link https://huggingface.co/organizations/ICML2022/share/BpynfJtfsOTktlmXYoKNqqCnyufKLFXuay, let me know if you need any help with the above steps, thanks

**Comment by yaoxingcheng** [comment]
Thanks for your information. I'll look into it.
