### ISSUE TITLE
year 2021 -> 2022 in citation section

### ISSUE THREAD

**Issue by Timothyxxx** [yaoxingcheng/TLM#18]
Hi, 

We are citing your paper and find you may make year wrong in citation. Maybe it should be year 2022?

Thanks

**Comment by yaoxingcheng** [comment]
Thanks for your helpful reminder.

The bibtex in `README.md` has been updated to [the official version of proceedings of ICML](https://proceedings.mlr.press/v162/yao22c.html).  The camera ready version of the paper will also be uploaded to Arxiv shortly.

**Comment by Timothyxxx** [comment]
Copy that! Nice work by the way, controllable pre-training is the future I believe.
