### ISSUE TITLE
How to make target dataset from source database ?

### ISSUE THREAD

**Issue by Huynh-Chinh** [yaoxingcheng/TLM#8]
Hi yaoxingcheng,

Thanks for releasing the code and paper for your task-driven language modeling approach.
I have some basic question about dataset construction:
I want to train a new model specifically roberta on my dataset. I already have my data as "my_source.csv". But i don't know how to build "my_tareget.csv". And I don't understand how to construct such data yet.
Can you help me solve this problem?

Best,
ChinhH

**Comment by yaoxingcheng** [comment]
Hi, ChinhH. The target data is a CSV file, with a column named "text", which represents the text string of each training sample. Optionally you can construct other fields in the CSV file for other customized usage.
