### ISSUE TITLE
Trying to Execute Code

### ISSUE THREAD

**Issue by Sheraz2136** [yaoxingcheng/TLM#9]
Hi I am trying to execute your code on pycharm but getting errors. Can you please let me know from where we can run the main function and what are the step by step function to execute the code as I am a newbie in programming. 
Also I have chosen your paper for ML reproducibility challenge.

**Comment by yaoxingcheng** [comment]
Hello~ The main function of the code is in `src/run.py` starting from line 435. You may follow the instructions in `README.md` to run the code.
